name: Deploy Portfolio
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, portfolio ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & deploy
        run: |
          cd "${{ github.workspace }}"
          # stop & remove any old containers (even if names changed)
          docker compose down --remove-orphans
          # rebuild and recreate everything
          docker compose up -d --force-recreate --remove-orphans --build
