name: Deploy Portfolio
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, portfolio ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & deploy
        run: |
          cd "${{ github.workspace }}"
          docker compose down
          docker compose up -d --build
